---
# Proxmox for iGPU Full Passthrough
# https://3os.org/infrastructure/proxmox/gpu-passthrough/igpu-passthrough-to-vm/

- name: Edit the grub configuration file
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    search_string: 'GRUB_CMDLINE_LINUX_DEFAULT'
    line: GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on iommu=pt pcie_acs_override=downstream,multifunction initcall_blacklist=sysfb_init video=simplefb:off video=vesafb:off video=efifb:off video=vesa:off disable_vga=1 vfio_iommu_type1.allow_unsafe_interrupts=1 kvm.ignore_msrs=1 modprobe.blacklist=radeon,nouveau,nvidia,nvidiafb,nvidia-gpu,snd_hda_intel,snd_hda_codec_hdmi,i915"
  notify: ['Update grub']
  become: true

- name: Add modules required for PCI passthrough
  ansible.builtin.blockinfile:
    path: /etc/modules
    block: |
      # Modules required for PCI passthrough
      vfio
      vfio_iommu_type1
      vfio_pci
      vfio_virqfd
  notify: ['Update initramfs']
  become: true
