---
- name: LXC Docker Plex
  hosts: lxc-docker-plex

  vars:
    docker_apps_dir: /srv/docker
    traefik_domain: omv.home

  roles:
    - role: docker
      vars:
        docker_apparmor: false
    - role: docker-traefik
    - role: docker-plex
      vars:
        plex_claim: claim-WjugPP9CPzxoyykmJUEU
    - role: docker-tautulli
...
