---
- name: LXC Docker Immich
  hosts: lxc-docker-immich

  vars:
    docker_apps_dir: /srv/docker
    root_domain: home

  pre_tasks:
    - name: Include vault
      ansible.builtin.include_vars:
        file: prod.vault.yml

  roles:
    - role: geerlingguy.docker
    - role: docker-traefik
    - role: docker-immich
      vars:
        immich_domain: immich.pve.{{ root_domain }}
        immich_docker_gid: 100
        immich_docker_uid: 1200
        immich_database_hostname: 10.0.0.103
        immich_database_password: "{{ immich_database_password }}"
