---
- name: OpenMediaVault 6
  hosts: omv6

  vars:
    docker_apps_dir: /srv/docker
    traefik_domain: omv.home

  pre_tasks:
    - name: Include vault
      ansible.builtin.include_vars:
        file: prod.vault.yml

  roles:
    - role: authorized-key
    - role: docker
    - role: docker-traefik
    - role: docker-sonarr
    - role: docker-radarr
    - role: docker-prowlarr
    - role: docker-recyclarr
    - role: docker-flaresolverr
    - role: docker-transmission
    - role: docker-jackett
    - role: docker-restic
      vars:
        restic_repository: s3:s3.us-west-002.backblazeb2.com/docker-apps
        restic_backup_volumes:
          - /srv/storage/docker-data/photoprism:/data/photoprism:ro
...
