---
- name: OpenMediaVault 6
  hosts: omv6

  vars:
    docker_apps_dir: /srv/docker
    traefik_domain: omv.home

  pre_tasks:
    - name: Include vault
      ansible.builtin.include_vars:
        file: prod.vault.yml

  roles:
    - role: authorized-key
    - role: omv-monitoring-alert
    - role: omv-snapraid-aio-script
      vars:
        omv_snapraid_aio_script_email_address: "{{ snapraid_email }}"
        omv_snapraid_aio_script_from_email_address: "{{ email }}"
        omv_snapraid_aio_script_delete_threshold: 800
        omv_snapraid_aio_script_update_threshold: 4000
        omv_snapraid_aio_script_services:
          - sonarr
          - radarr
          - readarr
          - prowlarr
          - recyclarr
          - transmission
          - tubearchivist
          - photoprism-mariadb
    - role: docker
    - role: docker-traefik
      vars:
        traefik_dasboard: true
        traefik_dns_challenge: false
        traefik_http_challenge: false
    - role: docker-sonarr
    - role: docker-radarr
    - role: docker-prowlarr
    - role: docker-recyclarr
    - role: docker-flaresolverr
    - role: docker-transmission
      vars:
        transmission_pass: "{{ password }}"
    - role: docker-jackett
    - role: docker-photoprism-mariadb
    - role: docker-kopia
      vars:
        kopia_password: "{{ password }}"
        kopia_repository_password: "{{ kopia_repository_password }}"
        kopia_snapshot_volumes:
          - "{{ docker_apps_dir }}/photoprism:/data/photoprism:ro"
    - role: docker-archivebox
      vars:
        archivebox_pass: "{{ password }}"
    - role: docker-tubearchivist
      vars:
        tubearchivist_pass: "{{ password }}"
        tubearchivist_elasticsearch_pass: "{{ password }}"
    - role: docker-kavita
    - role: docker-readarr
...
