---
- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: "{{ authorized_key_user }}"
    key: "{{ lookup('file', '/Users/rostislav/.ssh/id_rsa.pub') }}"

- name: Reset ssh connection to allow user changes to affect 'current login user'
  ansible.builtin.meta: reset_connection
