---
- name: Create a Photoprism directory if it does not exist
  ansible.builtin.file:
    path: "{{ docker_apps_dir }}/photoprism-mariadb"
    state: directory
    mode: "0755"

- name: Get docker user info
  ansible.builtin.user:
    name: docker
  register: user

- name: Set variables
  ansible.builtin.set_fact:
    docker_uid: "{{ user.uid }}"
    docker_gid: "{{ user.group }}"

- name: Template a "docker-compose.yml" file
  ansible.builtin.template:
    src: ./roles/docker-photoprism-mariadb/templates/docker-compose.yml.j2
    dest: "{{ docker_apps_dir }}/photoprism-mariadb/docker-compose.yml"
    mode: "0644"

- name: Start Photoprism with docker-compose
  community.docker.docker_compose:
    project_src: "{{ docker_apps_dir }}/photoprism-mariadb/"
