---
# Install Proxmox VE on Debian Buster
# https://pve.proxmox.com/wiki/Install_Proxmox_VE_on_Debian_Buster

- name: Add an /etc/hosts entry for IP address
  ansible.builtin.lineinfile:
    path: /etc/hosts
    search_string: '127.0.1.1'
    line: "{{ proxmox_ip }} {{ proxmox_host }}"
  become: true

- name: Add the Proxmox VE repository key
  ansible.builtin.get_url:
    url: http://download.proxmox.com/debian/proxmox-ve-release-6.x.gpg
    dest: /etc/apt/trusted.gpg.d/proxmox-ve-release-6.x.gpg
    mode: '0644'
  become: true

- name: Add the Proxmox VE repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] http://download.proxmox.com/debian/pve buster pve-no-subscription
  become: true

- name: Update your repository and system
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
  become: true

- name: Install os-prober
  ansible.builtin.apt:
    name:
      - os-prober
    state: absent
  become: true

- name: Install ifupdown2
  ansible.builtin.apt:
    name:
      - open-iscsi
      - ifupdown2
      - lshw
  become: true

- name: Remove Proxmox VE enterprise repository
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent
