---
- name: Install packages
  ansible.builtin.apt:
    name:
      - qemu-guest-agent
    state: present
    update_cache: true
  become: true

- name: Autoremove and clean packages
  ansible.builtin.apt:
    autoremove: true
    clean: true
  become: true

- name: Make sure Docker is running and enabled
  ansible.builtin.systemd:
    name: qemu-guest-agent
    daemon_reload: true
    state: started
    enabled: true
  become: true
