---
- name: Install packages
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose
    state: present
    update_cache: true

- name: Autoremove and clean packages
  ansible.builtin.apt:
    autoremove: true
    clean: true

- name: Make sure Docker is running and enabled
  ansible.builtin.systemd:
    name: docker
    daemon_reload: true
    state: started
    enabled: true

- name: Add the user 'docker'
  ansible.builtin.user:
    name: docker
    comment: Docker Apps User
    create_home: false
    uid: "{{ docker_uid }}"
    groups: users,docker
