---
- name: Install packages
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose
      - apparmor-utils
    state: present
    update_cache: true
  become: true

- name: Install apparmor-utils
  when: docker_apparmor
  ansible.builtin.apt:
    name:
      - apparmor-utils
    state: present
    update_cache: true
  become: true

- name: Autoremove and clean packages
  ansible.builtin.apt:
    autoremove: true
    clean: true
  become: true

- name: Make sure Docker is running and enabled
  ansible.builtin.systemd:
    name: docker
    daemon_reload: true
    state: started
    enabled: true
  become: true

- name: Add the user 'docker'
  ansible.builtin.user:
    name: docker
    comment: Docker Apps User
    create_home: false
    uid: "{{ docker_uid }}"
    groups: users,docker
  become: true

- name: Copy Docker daemon config
  ansible.builtin.copy:
    src: files/etc/docker/
    dest: /etc/docker/
    mode: u=rw,g=r,o=r

- name: Restart service Docker
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: docker

- name: Prune everything
  community.docker.docker_prune:
    containers: true
    images: true
    networks: true
    volumes: true
    builder_cache: true
