---
# Proxmox for iGPU Full Passthrough
# https://pve.proxmox.com/wiki/PCI_Passthrough
# https://pve.proxmox.com/wiki/PCI(e)_Passthrough
# https://3os.org/infrastructure/proxmox/gpu-passthrough/igpu-passthrough-to-vm/
# https://cetteup.com/216/how-to-use-an-intel-vgpu-for-plexs-hardware-accelerated-streaming-in-a-proxmox-vm/

- name: Edit the grub configuration file
  ansible.builtin.lineinfile:
    backup: true
    path: /etc/default/grub
    search_string: 'GRUB_CMDLINE_LINUX_DEFAULT'
    line: GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on iommu=pt video=efifb:off"
  notify: ['Update grub']
  become: true

- name: Add modules required for PCI passthrough
  ansible.builtin.blockinfile:
    path: /etc/modules
    block: |
      # Modules required for PCI passthrough
      vfio
      vfio_pci
      vfio_virqfd
      vfio_iommu_type1
  notify: ['Update initramfs']
  become: true

- name: Add vfio-pci options
  ansible.builtin.blockinfile:
    create: true
    mode: '0644'
    path: /etc/modprobe.d/vfio.conf
    block: |
      options vfio-pci ids=8086:3185 disable_vga=1
  notify: ['Update initramfs']
  become: true

- name: Allow unsafe interrupts
  ansible.builtin.blockinfile:
    create: true
    mode: '0644'
    path: /etc/modprobe.d/iommu.conf
    block: |
      options vfio_iommu_type1 allow_unsafe_interrupts=1
  notify: ['Update initramfs']
  become: true

- name: Blacklist drivers
  ansible.builtin.blockinfile:
    create: true
    mode: '0644'
    path: /etc/modprobe.d/blacklist.conf
    block: |
      blacklist sof_pci_dev
      blacklist snd_hda_intel
      blacklist snd_hda_codec_hdmi
      blacklist i915
  notify: ['Update initramfs']
  become: true

- name: Ignore msrs
  ansible.builtin.blockinfile:
    create: true
    mode: '0644'
    path: /etc/modprobe.d/kvm.conf
    block: |
      options kvm ignore_msrs=1 report_ignored_msrs=0
  notify: ['Update initramfs']
  become: true
