---
- name: Start the Wireguard container
  community.docker.docker_container:
    name: wg-easy
    image: weejewel/wg-easy:7
    pull: true
    state: started
    restart_policy: unless-stopped
    sysctls:
      "net.ipv4.conf.all.src_valid_mark": "1"
      "net.ipv4.ip_forward": "1"
    capabilities:
      - net_admin
      - sys_module
    env:
      "PASSWORD": "{{ wireguard_password }}"
      "WG_HOST": "{{ wireguard_host }}"
      "WG_PERSISTENT_KEEPALIVE": "25"
    ports:
      - "{{ wireguard_port }}:51820/udp"
    volumes:
      - "{{ docker_dir }}/wireguard:/etc/wireguard"
    labels:
      "traefik.enable": "true"
      "traefik.http.routers.wireguard.rule": "Host(`wg.{{ traefik_domain }}`)"
      "traefik.http.services.wireguard.loadbalancer.server.port": "51821"
    networks:
      - name: "{{ traefik_network_name }}"
