---
# Install Proxmox VE on Debian 11 Bullseye
# https://pve.proxmox.com/wiki/Install_Proxmox_VE_on_Debian_11_Bullseye

- name: Add an /etc/hosts entry for IP address
  ansible.builtin.lineinfile:
    path: /etc/hosts
    search_string: '127.0.1.1'
    line: "{{ proxmox7_ip }} {{ proxmox7_host }}"
  become: true

- name: Add the Proxmox VE repository key
  ansible.builtin.get_url:
    url: https://enterprise.proxmox.com/debian/proxmox-release-bullseye.gpg
    dest: /etc/apt/trusted.gpg.d/proxmox-release-bullseye.gpg
    mode: '0644'
  become: true

- name: Add the Proxmox VE repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] http://download.proxmox.com/debian/pve bullseye pve-no-subscription
  become: true

- name: Update repository and system
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
  become: true

- name: Install PVE kernel
  ansible.builtin.apt:
    name:
      - pve-kernel-5.15
    update_cache: true
  become: true
