---
- name: Create a Immich directory if it does not exist
  ansible.builtin.file:
    path: "{{ docker_apps_dir }}/immich"
    state: directory
    mode: "0755"

- name: Template a "docker-compose.yml" file
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: "{{ docker_apps_dir }}/immich/docker-compose.yml"
    mode: "0644"

- name: Start Immich with docker-compose
  community.docker.docker_compose_v2:
    pull: always
    project_src: "{{ docker_apps_dir }}/immich/"
